sudo: required
services:
  - docker

before_install:
  - docker build -t loki194/react-test -f ./myapp/Dockerfile.dev ./myapp

script:
  - docker run loki194/react-test npm test -- --coverage

after_success:
  - docker build -t loki194/deals-client ./myapp
  - docker build -t loki194/deals-nginx ./nginx
  - docker build -t loki194/deals-server ./server
  - docker build -t loki194/deals-worker ./worker

  # take these images and push to the docker-hub
  
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  - docker push loki194/deals-client
  - docker push loki194/deals-nginx
  - docker push loki194/deals-server
  - docker push loki194/deals-worker

deploy:
  provider: elasticbeanstalk
  region: us-east-2
  app: deals-docker
  env: DealsDocker-env
  bucket_name: elasticbeanstalk-us-east-2-327326504583
  bucket_path: docker-deals
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: $AWS_SECRET_KEY