version: "2"
services:
  nginx:
    restart: always
    image: 'nginx'
    build:
      context: ./nginx
    ports:
      - '5000:80'
  client:
    container_name: client
    build:
      dockerfile: Dockerfile.dev
      context: ./client
    volumes:
      - /usr/app/node_modules
      - ./myapp:/usr/app