version: "3"
services:
  nginx:
    restart: always
    image: 'nginx'
    build:
      dockerfile: Dockerfile.dev
      context: ./nginx
    ports:
      - '5000:80'
  client:
    # container_name: client
    build:
      # dockerfile: Dockerfile.dev
      context: ./client
    volumes:
      - /app/node_modules
      - ./client:/app